[tool.poetry]
name = "app"
version = "1.4.0"
description = ""
authors = ["Matteo Campinoti <matteo.campinoti94@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
faapi = "3.7.0"
fastapi = "0.75.2"
orjson = "3.6.8"
uvicorn = "0.17.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
